// Generated by scripts/render-ui-pages-from-browser.mjs. Do not edit manually.
export interface PrototypePageDefinition {
  slug: string
  filename: string
  title: string
  subtitle: string
  component: string
}

export const prototypePages: PrototypePageDefinition[] = [
  {
    "slug": "agent-control",
    "filename": "agent_control.html",
    "title": "アプリ制御",
    "subtitle": "アプリ/プロセス制御ルールの管理",
    "component": "AgentControlPage"
  },
  {
    "slug": "agent-history",
    "filename": "agent_history.html",
    "title": "エージェント状態",
    "subtitle": "端末エージェントのライブ状態とプロセス一覧",
    "component": "AgentHistoryPage"
  },
  {
    "slug": "ai-inputdialog1",
    "filename": "ai_inputdialog1.html",
    "title": "AI生成内容（ダイアログ）",
    "subtitle": "ai_inputdialog1.jsp のマッピング",
    "component": "AiInputdialog1Page"
  },
  {
    "slug": "ai-inputdialog2",
    "filename": "ai_inputdialog2.html",
    "title": "AI勉強内容（ダイアログ）",
    "subtitle": "ai_inputdialog2.jsp のマッピング",
    "component": "AiInputdialog2Page"
  },
  {
    "slug": "ai",
    "filename": "ai.html",
    "title": "AI英語学習",
    "subtitle": "AI によるコンテンツ生成とチャット",
    "component": "AiPage"
  },
  {
    "slug": "batch",
    "filename": "batch.html",
    "title": "バッチ管理",
    "subtitle": "バッチタスクの監視・手動実行",
    "component": "BatchPage"
  },
  {
    "slug": "daily-report",
    "filename": "daily_report.html",
    "title": "学習日報",
    "subtitle": "今日の学習を記録・振り返り",
    "component": "DailyReportPage"
  },
  {
    "slug": "design-system",
    "filename": "design-system.html",
    "title": "STUDY 2.0 — Design System",
    "subtitle": "",
    "component": "DesignSystemPage"
  },
  {
    "slug": "document-inputdialog1",
    "filename": "document_inputdialog1.html",
    "title": "資料詳細（ダイアログ）",
    "subtitle": "document_inputdialog1.jsp のマッピング",
    "component": "DocumentInputdialog1Page"
  },
  {
    "slug": "document-showpic",
    "filename": "document_showpic.html",
    "title": "画像表示",
    "subtitle": "",
    "component": "DocumentShowpicPage"
  },
  {
    "slug": "document",
    "filename": "document.html",
    "title": "資料管理",
    "subtitle": "資料の 4 級分類・ファイル管理",
    "component": "DocumentPage"
  },
  {
    "slug": "english-cloze",
    "filename": "english_cloze.html",
    "title": "英語穴埋め問題",
    "subtitle": "画像 OCR → 設問確認 → AI 解説生成",
    "component": "EnglishClozePage"
  },
  {
    "slug": "english-essay",
    "filename": "english_essay.html",
    "title": "英作文AI添削",
    "subtitle": "画像アップロード → OCR → AI 添削レポート",
    "component": "EnglishEssayPage"
  },
  {
    "slug": "english-grammar-input",
    "filename": "english_grammar_input.html",
    "title": "文法登録",
    "subtitle": "文法知識の登録・編集（english_grammar_input.jsp の再現）",
    "component": "EnglishGrammarInputPage"
  },
  {
    "slug": "english-grammar",
    "filename": "english_grammar.html",
    "title": "英語文法管理",
    "subtitle": "文法知識のカテゴリ別管理",
    "component": "EnglishGrammarPage"
  },
  {
    "slug": "english-reading-input",
    "filename": "english_reading_input.html",
    "title": "英語読書書籍登録",
    "subtitle": "書籍の登録（english_reading_input.jsp の再現）",
    "component": "EnglishReadingInputPage"
  },
  {
    "slug": "english-reading-intensive",
    "filename": "english_reading_intensive.html",
    "title": "英語読解・精読",
    "subtitle": "AI パイプラインによる精読教材の管理・学習",
    "component": "EnglishReadingIntensivePage"
  },
  {
    "slug": "english-reading-reader",
    "filename": "english_reading_reader.html",
    "title": "英語読書閲覧",
    "subtitle": "PDF リーダーと標記ツール",
    "component": "EnglishReadingReaderPage"
  },
  {
    "slug": "english-reading",
    "filename": "english_reading.html",
    "title": "英語読書管理",
    "subtitle": "書籍の登録・読書履歴の管理",
    "component": "EnglishReadingPage"
  },
  {
    "slug": "english-word-textbook-group",
    "filename": "english_word_textbook_group.html",
    "title": "英単語教材取込",
    "subtitle": "6 ステップの教材処理ウィザード",
    "component": "EnglishWordTextbookGroupPage"
  },
  {
    "slug": "english-word-textbook",
    "filename": "english_word_textbook.html",
    "title": "英単語教材取込",
    "subtitle": "教材取込グループ（バッチ）の一覧管理",
    "component": "EnglishWordTextbookPage"
  },
  {
    "slug": "english",
    "filename": "english.html",
    "title": "英語勉強",
    "subtitle": "英語学習の進捗と統計",
    "component": "EnglishPage"
  },
  {
    "slug": "game",
    "filename": "game.html",
    "title": "ゲーム",
    "subtitle": "マインスイーパー / 五目並べ",
    "component": "GamePage"
  },
  {
    "slug": "geometry-draw",
    "filename": "geometry_draw.html",
    "title": "図形作成",
    "subtitle": "",
    "component": "GeometryDrawPage"
  },
  {
    "slug": "geometry",
    "filename": "geometry.html",
    "title": "図形一覧",
    "subtitle": "GeoGebra 図形・関数グラフの管理",
    "component": "GeometryPage"
  },
  {
    "slug": "history-fixed",
    "filename": "history_fixed.html",
    "title": "履歴管理（簡易版）",
    "subtitle": "上網 / バッチの履歴（history_fixed.jsp の再現）",
    "component": "HistoryFixedPage"
  },
  {
    "slug": "history",
    "filename": "history.html",
    "title": "履歴管理",
    "subtitle": "上網 / ブラウザ / バッチ / AI 呼出の履歴",
    "component": "HistoryPage"
  },
  {
    "slug": "home",
    "filename": "home.html",
    "title": "ホーム",
    "subtitle": "今日の学習状況とスケジュール",
    "component": "HomePage"
  },
  {
    "slug": "japanese-test-a",
    "filename": "japanese_test_a.html",
    "title": "日本語 A.勉強",
    "subtitle": "",
    "component": "JapaneseTestAPage"
  },
  {
    "slug": "japanese-test-b",
    "filename": "japanese_test_b.html",
    "title": "日本語 B.意味→日本語",
    "subtitle": "",
    "component": "JapaneseTestBPage"
  },
  {
    "slug": "japanese-test-c",
    "filename": "japanese_test_c.html",
    "title": "日本語 C.漢字→読み",
    "subtitle": "",
    "component": "JapaneseTestCPage"
  },
  {
    "slug": "japanese-test-d",
    "filename": "japanese_test_d.html",
    "title": "日本語 D.文脈詞義判断",
    "subtitle": "",
    "component": "JapaneseTestDPage"
  },
  {
    "slug": "japanese-test-demo",
    "filename": "japanese_test_demo.html",
    "title": "日本語単語テスト（Demo）",
    "subtitle": "",
    "component": "JapaneseTestDemoPage"
  },
  {
    "slug": "japanese-test-e",
    "filename": "japanese_test_e.html",
    "title": "日本語 E.漢字選択",
    "subtitle": "",
    "component": "JapaneseTestEPage"
  },
  {
    "slug": "japanese-test",
    "filename": "japanese_test.html",
    "title": "日本語単語テスト",
    "subtitle": "日本語単語テストの一覧と開始",
    "component": "JapaneseTestPage"
  },
  {
    "slug": "japanese-word-status",
    "filename": "japanese_word_status.html",
    "title": "日本語単語勉強状況",
    "subtitle": "種別（B～E）ごとの習得状況",
    "component": "JapaneseWordStatusPage"
  },
  {
    "slug": "japanese-word",
    "filename": "japanese_word.html",
    "title": "日本語単語情報管理",
    "subtitle": "日本語単語のマスターデータ管理",
    "component": "JapaneseWordPage"
  },
  {
    "slug": "japanese",
    "filename": "japanese.html",
    "title": "日本語勉強",
    "subtitle": "日本語学習の進捗と統計",
    "component": "JapanesePage"
  },
  {
    "slug": "link-clip-demo",
    "filename": "link_clip_demo.html",
    "title": "リンククリップ DEMO",
    "subtitle": "リンク保存のプロトタイプ",
    "component": "LinkClipDemoPage"
  },
  {
    "slug": "math-knowledge-input",
    "filename": "math_knowledge_input.html",
    "title": "数学知識点新規登録",
    "subtitle": "知識点の登録・編集（math_knowledge_input.jsp の再現）",
    "component": "MathKnowledgeInputPage"
  },
  {
    "slug": "math-knowledge",
    "filename": "math_knowledge.html",
    "title": "数学知識点管理",
    "subtitle": "知識点の検索・学習・編集",
    "component": "MathKnowledgePage"
  },
  {
    "slug": "math-wrong-input",
    "filename": "math_wrong_input.html",
    "title": "誤問題登録",
    "subtitle": "誤問題の登録・編集（math_wrong_input.jsp の再現）",
    "component": "MathWrongInputPage"
  },
  {
    "slug": "math-wrong-inputdialog1",
    "filename": "math_wrong_inputdialog1.html",
    "title": "誤問題の復習（旧ダイアログ）",
    "subtitle": "math_wrong_inputdialog1.jsp のマッピング（孤立片段）",
    "component": "MathWrongInputdialog1Page"
  },
  {
    "slug": "math-wrong-review",
    "filename": "math_wrong_review.html",
    "title": "誤問題の復習",
    "subtitle": "解き直し・知識点復習",
    "component": "MathWrongReviewPage"
  },
  {
    "slug": "math-wrong-showoic",
    "filename": "math_wrong_showoic.html",
    "title": "解答写真表示",
    "subtitle": "",
    "component": "MathWrongShowoicPage"
  },
  {
    "slug": "math-wrong",
    "filename": "math_wrong.html",
    "title": "誤問題集",
    "subtitle": "誤問題の一覧・修正・復習",
    "component": "MathWrongPage"
  },
  {
    "slug": "math",
    "filename": "math.html",
    "title": "数学勉強",
    "subtitle": "誤問題の分野・原因・知識点を分析して弱点を見える化",
    "component": "MathPage"
  },
  {
    "slug": "menu-inputdialog1",
    "filename": "menu_inputdialog1.html",
    "title": "システム設定（旧ダイアログ）",
    "subtitle": "menu_inputdialog1.jsp の再現",
    "component": "MenuInputdialog1Page"
  },
  {
    "slug": "mindmap",
    "filename": "mindmap.html",
    "title": "思維導図",
    "subtitle": "学習内容をマインドマップで整理（Demo・localStorage 保存）",
    "component": "MindmapPage"
  },
  {
    "slug": "phrase-test-a",
    "filename": "phrase_test_a.html",
    "title": "熟語 A. 勉強",
    "subtitle": "",
    "component": "PhraseTestAPage"
  },
  {
    "slug": "phrase-test-b",
    "filename": "phrase_test_b.html",
    "title": "熟語 B. 意味 → 表現",
    "subtitle": "",
    "component": "PhraseTestBPage"
  },
  {
    "slug": "phrase-test-c",
    "filename": "phrase_test_c.html",
    "title": "熟語 C. 音声 → 表現",
    "subtitle": "",
    "component": "PhraseTestCPage"
  },
  {
    "slug": "phrase-test-d",
    "filename": "phrase_test_d.html",
    "title": "熟語 D. 文脈 → 意味",
    "subtitle": "",
    "component": "PhraseTestDPage"
  },
  {
    "slug": "phrase-test-e",
    "filename": "phrase_test_e.html",
    "title": "熟語 E. 構文・穴埋め",
    "subtitle": "",
    "component": "PhraseTestEPage"
  },
  {
    "slug": "phrase-test",
    "filename": "phrase_test.html",
    "title": "熟語テスト",
    "subtitle": "熟語テストの一覧と開始",
    "component": "PhraseTestPage"
  },
  {
    "slug": "setting",
    "filename": "setting.html",
    "title": "システム設定",
    "subtitle": "翻訳、発音、AIモデル、単語・熟語詳細知識、画像処理、OCR、英作文、英語読解・精読、学習日報、学習モニター、外部連携の設定を一元管理します。",
    "component": "SettingPage"
  },
  {
    "slug": "site-inputdialog1",
    "filename": "site_inputdialog1.html",
    "title": "サイト新規登録（ダイアログ）",
    "subtitle": "site_inputdialog1.jsp のマッピング",
    "component": "SiteInputdialog1Page"
  },
  {
    "slug": "site",
    "filename": "site.html",
    "title": "サイト一覧",
    "subtitle": "サイト URL ルールの管理（承認・有効/無効）",
    "component": "SitePage"
  },
  {
    "slug": "study-focus",
    "filename": "study_focus.html",
    "title": "学習タイマー",
    "subtitle": "",
    "component": "StudyFocusPage"
  },
  {
    "slug": "study-monitor",
    "filename": "study_monitor.html",
    "title": "学習状況モニター",
    "subtitle": "カメラ映像の AI 分析・手動修正・タイムライン",
    "component": "StudyMonitorPage"
  },
  {
    "slug": "temp-file-picker",
    "filename": "temp_file_picker.html",
    "title": "臨時ファイル選択",
    "subtitle": "",
    "component": "TempFilePickerPage"
  },
  {
    "slug": "temp-file-upload-note-copy",
    "filename": "temp_file_upload_note - 副本.html",
    "title": "メモノート（副本）",
    "subtitle": "",
    "component": "TempFileUploadNoteCopyPage"
  },
  {
    "slug": "temp-file-upload-note",
    "filename": "temp_file_upload_note.html",
    "title": "メモノート",
    "subtitle": "",
    "component": "TempFileUploadNotePage"
  },
  {
    "slug": "temp-file-upload",
    "filename": "temp_file_upload.html",
    "title": "臨時ファイルアップロード",
    "subtitle": "",
    "component": "TempFileUploadPage"
  },
  {
    "slug": "temp-file",
    "filename": "temp_file.html",
    "title": "臨時ファイル管理",
    "subtitle": "臨時ファイルの検索・編集・ダウンロード",
    "component": "TempFilePage"
  },
  {
    "slug": "terminal-control",
    "filename": "terminal_control.html",
    "title": "端末コントロール",
    "subtitle": "端末モードの一括・個別切替（parent）",
    "component": "TerminalControlPage"
  },
  {
    "slug": "testinfo-file-picker",
    "filename": "testinfo_file_picker.html",
    "title": "テスト情報ファイル選択",
    "subtitle": "",
    "component": "TestinfoFilePickerPage"
  },
  {
    "slug": "testinfo-inputdialog1",
    "filename": "testinfo_inputdialog1.html",
    "title": "テスト新規（ダイアログ）",
    "subtitle": "testinfo_inputdialog1.jsp のマッピング",
    "component": "TestinfoInputdialog1Page"
  },
  {
    "slug": "testinfo-showpic",
    "filename": "testinfo_showpic.html",
    "title": "試験用紙写真表示",
    "subtitle": "",
    "component": "TestinfoShowpicPage"
  },
  {
    "slug": "testinfo",
    "filename": "testinfo.html",
    "title": "テスト情報管理",
    "subtitle": "試験結果と試験用紙の管理",
    "component": "TestinfoPage"
  },
  {
    "slug": "testword-init",
    "filename": "testword_init.html",
    "title": "テスト開始",
    "subtitle": "",
    "component": "TestwordInitPage"
  },
  {
    "slug": "testword-inputdialog1",
    "filename": "testword_inputdialog1.html",
    "title": "複数作成（ダイアログ）",
    "subtitle": "testword_inputdialog1.jsp のマッピング",
    "component": "TestwordInputdialog1Page"
  },
  {
    "slug": "testword-inputdialog2",
    "filename": "testword_inputdialog2.html",
    "title": "単語リスト（ダイアログ）",
    "subtitle": "testword_inputdialog2.jsp のマッピング",
    "component": "TestwordInputdialog2Page"
  },
  {
    "slug": "testword",
    "filename": "testword.html",
    "title": "単語テスト",
    "subtitle": "単語テストの作成・一覧・開始",
    "component": "TestwordPage"
  },
  {
    "slug": "testword2-inputdialog1",
    "filename": "testword2_inputdialog1.html",
    "title": "複数作成（中級編・ダイアログ）",
    "subtitle": "testword2_inputdialog1.jsp のマッピング",
    "component": "Testword2Inputdialog1Page"
  },
  {
    "slug": "testword2",
    "filename": "testword2.html",
    "title": "単語テスト（転送）",
    "subtitle": "",
    "component": "Testword2Page"
  },
  {
    "slug": "testworld-test-a",
    "filename": "testworld_test_a.html",
    "title": "A.勉強",
    "subtitle": "",
    "component": "TestworldTestAPage"
  },
  {
    "slug": "testworld-test-b",
    "filename": "testworld_test_b.html",
    "title": "B.中日訳英",
    "subtitle": "",
    "component": "TestworldTestBPage"
  },
  {
    "slug": "testworld-test-c",
    "filename": "testworld_test_c.html",
    "title": "C.音訳英",
    "subtitle": "",
    "component": "TestworldTestCPage"
  },
  {
    "slug": "testworld-test-d",
    "filename": "testworld_test_d.html",
    "title": "D.英訳",
    "subtitle": "",
    "component": "TestworldTestDPage"
  },
  {
    "slug": "testworld-test-z",
    "filename": "testworld_test_z.html",
    "title": "単語学習 Demo",
    "subtitle": "",
    "component": "TestworldTestZPage"
  },
  {
    "slug": "testworld2-test-a",
    "filename": "testworld2_test_a.html",
    "title": "中級編 A.勉強",
    "subtitle": "",
    "component": "Testworld2TestAPage"
  },
  {
    "slug": "testworld2-test-b",
    "filename": "testworld2_test_b.html",
    "title": "中級編 B.中日訳英",
    "subtitle": "",
    "component": "Testworld2TestBPage"
  },
  {
    "slug": "testworld2-test-c",
    "filename": "testworld2_test_c.html",
    "title": "中級編 C.音訳英",
    "subtitle": "",
    "component": "Testworld2TestCPage"
  },
  {
    "slug": "testworld2-test-d",
    "filename": "testworld2_test_d.html",
    "title": "中級編 D.英訳中日",
    "subtitle": "",
    "component": "Testworld2TestDPage"
  },
  {
    "slug": "testworld2-test-e",
    "filename": "testworld2_test_e.html",
    "title": "中級編 E.文脈英訳",
    "subtitle": "",
    "component": "Testworld2TestEPage"
  },
  {
    "slug": "testworld2-test-f",
    "filename": "testworld2_test_f.html",
    "title": "中級編 F.例文入力",
    "subtitle": "",
    "component": "Testworld2TestFPage"
  },
  {
    "slug": "todo",
    "filename": "todo.html",
    "title": "TODO",
    "subtitle": "親Task・子Taskの管理",
    "component": "TodoPage"
  },
  {
    "slug": "word-ai",
    "filename": "word_ai.html",
    "title": "AI説明",
    "subtitle": "",
    "component": "WordAiPage"
  },
  {
    "slug": "word-inputdialog1",
    "filename": "word_inputdialog1.html",
    "title": "単語登録・編集（ダイアログ）",
    "subtitle": "word_inputdialog1.jsp のマッピング",
    "component": "WordInputdialog1Page"
  },
  {
    "slug": "word-question-fix",
    "filename": "word_question_fix.html",
    "title": "D問題補正",
    "subtitle": "D（英訳中日）問題の補正",
    "component": "WordQuestionFixPage"
  },
  {
    "slug": "word-status-mastery",
    "filename": "word_status_mastery.html",
    "title": "単語習得標識",
    "subtitle": "",
    "component": "WordStatusMasteryPage"
  },
  {
    "slug": "word-status",
    "filename": "word_status.html",
    "title": "単語勉強状況",
    "subtitle": "単語ごとの学習状況を種別（A～F）ごとに管理",
    "component": "WordStatusPage"
  },
  {
    "slug": "word",
    "filename": "word.html",
    "title": "単語情報管理",
    "subtitle": "単語・熟語のマスターデータ管理",
    "component": "WordPage"
  }
]

export const prototypePageMap = new Map(prototypePages.map((page) => [page.slug, page]))
